## 1. Liste Örnekleri

Python'da listeler, birden fazla veri tipini bir arada tutabilen dinamik veri yapılarıdır. İşte çeşitli liste işlemleri:

**Liste Tanımlama ve Temel İşlemler**



In [1]:
# Liste tanımlama
my_list = [1, 2, 3, 4, 5]

# Listeye eleman ekleme
my_list.append(6)  # Liste sonuna eleman ekler
print(my_list)  # [1, 2, 3, 4, 5, 6]

# Listeden eleman çıkarma
my_list.remove(3)  # 3'ü listeden çıkarır
print(my_list)  # [1, 2, 4, 5, 6]

# Liste elemanlarına erişim
print(my_list[0])  # İlk eleman: 1
print(my_list[-1])  # Son eleman: 6

# Liste dilimleme
print(my_list[1:4])  # [2, 4, 5]


[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
1
6
[2, 4, 5]


**Liste Döngüleri**

In [2]:
# Liste üzerinde döngü kurma
for element in my_list:
    print(element)

# Liste elemanlarını koşula göre işleme
even_numbers = [x for x in my_list if x % 2 == 0]  # Çift sayılar
print(even_numbers)  # [2, 4, 6]


1
2
4
5
6
[2, 4, 6]


**Liste Fonksiyonları**

In [3]:
# Liste uzunluğu
print(len(my_list))  # Liste uzunluğu: 5

# Listenin en büyük ve en küçük elemanı
print(max(my_list))  # Maksimum değer: 6
print(min(my_list))  # Minimum değer: 1

# Listeyi tersine çevirme
my_list.reverse()
print(my_list)  # [6, 5, 4, 2, 1]

# Listeyi sıralama
my_list.sort()
print(my_list)  # [1, 2, 4, 5, 6]


5
6
1
[6, 5, 4, 2, 1]
[1, 2, 4, 5, 6]


## Diziler

Python'da dizi (array) yapısı aslında varsayılan olarak gelmez; Python listeleri, dinamik boyutlu ve esnek oldukları için genellikle dizi yerine kullanılır. Ancak, Python'da dizilere özgü özellikler ve daha hızlı işlem yapma imkanı sunan bir kütüphane vardır: NumPy. NumPy, büyük verilerle ve çok boyutlu dizilerle çalışmak için özel olarak tasarlanmış bir kütüphanedir.

In [5]:
import numpy as np

# Tek boyutlu bir dizi (vektör)
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

# Çok boyutlu dizi (matris)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


 **Dizileri ile İşlemler**

NumPy dizileri ile toplama, çıkarma, çarpma gibi işlemleri hızlıca yapabilirsiniz. Ayrıca bu diziler üzerinde matematiksel ve istatistiksel fonksiyonlar da mevcuttur.

Temel Matematiksel İşlemler

In [6]:
# Dizideki tüm elemanları 2 ile çarpalım
multiplied_array = my_array * 2
print(multiplied_array)  # [ 2  4  6  8 10]

# Dizideki elemanların karesini alalım
squared_array = my_array ** 2
print(squared_array)  # [ 1  4  9 16 25]


[ 2  4  6  8 10]
[ 1  4  9 16 25]


**İstatistiksel İşlemler**

In [7]:
# Dizideki elemanların toplamı
print(np.sum(my_array))  # 15

# Dizideki en büyük ve en küçük eleman
print(np.max(my_array))  # 5
print(np.min(my_array))  # 1

# Dizinin ortalaması
print(np.mean(my_array))  # 3.0


15
5
1
3.0


**Çok Boyutlu Diziler (Matrisler)**

NumPy ile çok boyutlu diziler, yani matrisler oluşturabilirsiniz. Bu matrisler üzerinde transpoz alma, matris çarpımı gibi işlemler yapılabilir.

Çok Boyutlu Dizi Tanımlama

In [8]:
# 2x3 boyutunda bir dizi
matrix = np.array([[1, 2, 3], [4, 5, 6]])



[[1 4]
 [2 5]
 [3 6]]
